parameters:
    oro_sso.oauth_provider.class: Oro\Bundle\SSOBundle\Security\Core\User\OAuthUserProvider
    hwi_oauth.authentication.provider.oauth.class: Oro\Bundle\SSOBundle\Security\OAuthProvider
    hwi_oauth.resource_owner.google.class: Oro\Bundle\SSOBundle\OAuth\ResourceOwner\GoogleResourceOwner

services:
    oro_sso.oauth_provider:
        class:     %oro_sso.oauth_provider.class%
        arguments: [@oro_user.manager, @oro_config.global]
